export const pacienteInput = document.querySelector("#paciente")
export const propietarioInput = document.querySelector("#propietario")
export const emailInput = document.querySelector("#email")
export const fechaInput = document.querySelector("#fecha")
export const sintomasInput = document.querySelector("#sintomas")
export const form = document.querySelector("#formulario-cita")
export const listaCitas = document.querySelector("#citas")
export const sumbitInput = document.querySelector(`input[type="submit"]`)